/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Canvas: typeof import('./components/Canvas.vue')['default']
    Collapse: typeof import('./components/Collapse.vue')['default']
    ContentDropMenu: typeof import('./components/ContentDropMenu.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    CPopselect: typeof import('./components/CPopselect.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    NotOptimized: typeof import('./components/NotOptimized.vue')['default']
    PathCanvas: typeof import('./components/playground/PathCanvas.vue')['default']
    PathCanvasContextMenu: typeof import('./components/playground/PathCanvasContextMenu.vue')['default']
    PathPropertyPanel: typeof import('./components/playground/PathPropertyPanel.vue')['default']
    PathToolsPanel: typeof import('./components/playground/PathToolsPanel.vue')['default']
    PreviewCode: typeof import('./components/PreviewCode.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slide: typeof import('./components/Slide.vue')['default']
    SvgBox: typeof import('./components/SvgBox.vue')['default']
    ToolButton: typeof import('./components/ToolButton.vue')['default']
  }
}
