/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AllPathData: typeof import('./components/playground/SidePanel/AllPathData.vue')['default']
    Canvas: typeof import('./components/playground/PathCanvas/Canvas.vue')['default']
    CCollapse: typeof import('./components/ui/CCollapse.vue')['default']
    Command: typeof import('./components/playground/SidePanel/Command.vue')['default']
    Configuration: typeof import('./components/playground/SidePanel/Configuration.vue')['default']
    ContentDropMenu: typeof import('./components/ui/ContentDropMenu.vue')['default']
    ContextMenu: typeof import('./components/playground/PathCanvas/ContextMenu.vue')['default']
    CPopselect: typeof import('./components/ui/CPopselect.vue')['default']
    Footer: typeof import('./components/ui/Footer.vue')['default']
    PathCanvas: typeof import('./components/playground/PathCanvas/index.vue')['default']
    PathOperations: typeof import('./components/playground/SidePanel/PathOperations.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidePanel: typeof import('./components/playground/SidePanel/index.vue')['default']
    ToolBar: typeof import('./components/playground/ToolBar/index.vue')['default']
  }
}
